# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle     Tn = n(n+1)/2     1, 3, 6, 10, 15, ...
# Pentagonal   Pn = n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal    Hn = n(2n−1)      1, 6, 15, 28, 45, ...
# It can be verified that T_285 = P_165 = H_143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

def is_triangle(T_n):
    return (1 + 8*T_n)**0.5 % 2 == 1

def is_pentagonal(P_n):
    return (1 + 24*P_n)**0.5 % 6 == 5

def is_hexagonal(H_n):
    return (1 + 8*H_n)**0.5 % 4 == 3

def get_n_triangle(T_n):
    return int((1 + 8*T_n)**0.5 // 2)

def next_triangle(current_triangle):
    current_n = get_n_triangle(current_triangle)
    return int((current_n + 1) * (current_n + 2) // 2)

def main():
    number = next_triangle(40755)
    print(number)
    while True:
        if is_triangle(number) and is_pentagonal(number) and is_hexagonal(number):
            print(number)
            break
        number = next_triangle(number)

if __name__ == '__main__':
    main()
